<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Czytaj Wicej_post-thumbnail-rollover_1_2</name>
   <tag></tag>
   <elementGuidId>bf1d2458-c214-4483-abe6-906c78cf0ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>article.post.project-odd.visible.post-3328.type-post.status-publish.format-standard.has-post-thumbnail.hentry.category-artykuly.category-58 > div.post-thumbnail-wrap > div.post-thumbnail > a.post-thumbnail-rollover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div/div/div[2]/div[4]/article/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.aptekarska.pl/2020/12/03/plukanki-zawierajace-oktenidyne-i-fenoksyetanol-istotnie-zmniejszaja-poziom-wirusa-sars-cov-2-na-blonach-sluzowych/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>post-thumbnail-rollover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;vc_row wpb_row vc_row-fluid vc_custom_1580210562158 vc_row-no-padding&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-12&quot;]/div[@class=&quot;vc_column-inner&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;blog-shortcode blog-masonry-shortcode-id-c6ebd3298884ace2a7c4923d606caf5c mode-grid classic-layout-list content-bg-on jquery-filter dt-css-grid-wrap enable-bg-rollover dt-icon-bg-off resize-by-browser-width loading-effect-none description-under-image&quot;]/div[@class=&quot;dt-css-grid&quot;]/div[@class=&quot;visible wf-cell category-58 shown&quot;]/article[@class=&quot;post project-odd visible post-3328 type-post status-publish format-standard has-post-thumbnail hentry category-artykuly category-58&quot;]/div[@class=&quot;post-thumbnail-wrap&quot;]/div[@class=&quot;post-thumbnail&quot;]/a[@class=&quot;post-thumbnail-rollover&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/div/div[2]/div[4]/article/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Czytaj Więcej'])[3]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beata Tyszkiewicz-Kmiecik'])[2]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artykuły'])[8]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.aptekarska.pl/2020/12/03/plukanki-zawierajace-oktenidyne-i-fenoksyetanol-istotnie-zmniejszaja-poziom-wirusa-sars-cov-2-na-blonach-sluzowych/')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/article/div/div/a</value>
   </webElementXpaths>
</WebElementEntity>
