<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sortuj po dacie_filter-switch-toggle</name>
   <tag></tag>
   <elementGuidId>fb07a121-6479-4559-b898-70e4e1370f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.filter-switch-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div/div/div/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-switch-toggle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;vc_row wpb_row vc_row-fluid vc_custom_1580210562158 vc_row-no-padding&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-12&quot;]/div[@class=&quot;vc_column-inner&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;blog-shortcode blog-masonry-shortcode-id-c6ebd3298884ace2a7c4923d606caf5c mode-grid classic-layout-list content-bg-on jquery-filter dt-css-grid-wrap enable-bg-rollover dt-icon-bg-off resize-by-browser-width loading-effect-none description-under-image&quot;]/div[@class=&quot;iso-filter css-grid-filter filter-bg-decoration filter&quot;]/div[@class=&quot;filter-extras&quot;]/div[@class=&quot;filter-by&quot;]/span[@class=&quot;filter-switch left-act pressed&quot;]/span[@class=&quot;filter-switch-toggle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/div/div/div/div/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span</value>
   </webElementXpaths>
</WebElementEntity>
