<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Wybierz wszystkie zdjcia, na ktrych s palmy</name>
   <tag></tag>
   <elementGuidId>3182a8e8-3cdf-46c9-9f2d-82e61b5071ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rc-imageselect-desc-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect']/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-imageselect-desc-wrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wybierz wszystkie zdjęcia, na których są palmy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect&quot;)/div[@class=&quot;rc-imageselect-payload&quot;]/div[@class=&quot;rc-imageselect-instructions&quot;]/div[@class=&quot;rc-imageselect-desc-wrapper&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Formularz/Page_Aptekarska Szkoa Zarzdzania/iframe_Niepoprawny adres email_c-6mxxpk82ip3v</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect']/div[2]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
