<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_palmy_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>42fe9d94-6526-49a0-9336-49e1e1086776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq24tYd6cuh43a4JoYtGhRMo09WcYeq8A2JI2HRdsXE7-q77K6FFG7iox5VupsotsZ9lgdbwkEYRqgTEUirK7hW8p8TA2PCFff6H43n-7f--m7GJZMdGbY-w1wQvaERW3m34wCJgzd2pDJUeyHqOwIITVnOJf8FKBRmyFTgWglVkcBtmtL7wXK0oxP4zMxLyxXfmNwod7&amp;k=6LdShToUAAAAAOIhE7oWA-YalXGYv3KnRnokkunq</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Formularz/Page_Aptekarska Szkoa Zarzdzania/iframe_Niepoprawny adres email_c-6mxxpk82ip3v</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq24tYd6cuh43a4JoYtGhRMo09WcYeq8A2JI2HRdsXE7-q77K6FFG7iox5VupsotsZ9lgdbwkEYRqgTEUirK7hW8p8TA2PCFff6H43n-7f--m7GJZMdGbY-w1wQvaERW3m34wCJgzd2pDJUeyHqOwIITVnOJf8FKBRmyFTgWglVkcBtmtL7wXK0oxP4zMxLyxXfmNwod7&amp;k=6LdShToUAAAAAOIhE7oWA-YalXGYv3KnRnokkunq')])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
