<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rowery_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>b16350fb-b918-44c0-aafc-dd8cfccfd87e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq24fqMbypmKym8xZhnIgkk4cxMTZPHfE1W_NkMuhuGXQN6LGLd5JOw5IyjnttZ0r9m9kIUFuNvNWAtJ3MOJwWmUctpcF4upRTflggC4tAn2s-Hh50zLiWGJyKhqlMCoCvF4ZnDRrQgECORI0MzKdhxKU_iUbSfjRmgSK_0DYv1yvSQdd6_-YLyWNj5db-cm63gXhVHI8&amp;k=6LdShToUAAAAAOIhE7oWA-YalXGYv3KnRnokkunq</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Formularz/Page_Aptekarska Szkoa Zarzdzania/iframe_Niepoprawny adres email_c-o6zycoreunuo</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq24fqMbypmKym8xZhnIgkk4cxMTZPHfE1W_NkMuhuGXQN6LGLd5JOw5IyjnttZ0r9m9kIUFuNvNWAtJ3MOJwWmUctpcF4upRTflggC4tAn2s-Hh50zLiWGJyKhqlMCoCvF4ZnDRrQgECORI0MzKdhxKU_iUbSfjRmgSK_0DYv1yvSQdd6_-YLyWNj5db-cm63gXhVHI8&amp;k=6LdShToUAAAAAOIhE7oWA-YalXGYv3KnRnokkunq')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
