<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_sygnalizacj wietln_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>08f0f7fb-4057-4792-a4ce-c55c763e9f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq242JcWuEixY621pVRk8PiaMGXTlgtM_kGXpknayqSe_lgs-8B5Ugp8cwIKK5qT793xl1jDY2zeGUs9llxwPliggGY-6ZpLaGjbelCpuZIdnHkDJacSIGLteios0JlRl3TUmEpXlBKxSzCbhsBfu7GsB-WYef6RBmJSu2mfLRfHEKRF7GsIknZ914G5N0Sh7dxVF5k2TFOyC6xyQOPwGCSoiFRSKrw&amp;k=6LdShToUAAAAAOIhE7oWA-YalXGYv3KnRnokkunq</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Formularz/Page_Aptekarska Szkoa Zarzdzania/iframe_Niepoprawny adres email_c-o6zycoreunuo</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq242JcWuEixY621pVRk8PiaMGXTlgtM_kGXpknayqSe_lgs-8B5Ugp8cwIKK5qT793xl1jDY2zeGUs9llxwPliggGY-6ZpLaGjbelCpuZIdnHkDJacSIGLteios0JlRl3TUmEpXlBKxSzCbhsBfu7GsB-WYef6RBmJSu2mfLRfHEKRF7GsIknZ914G5N0Sh7dxVF5k2TFOyC6xyQOPwGCSoiFRSKrw&amp;k=6LdShToUAAAAAOIhE7oWA-YalXGYv3KnRnokkunq')])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
