<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_sygnalizacj wietln_rc-image-tile-44 (1)</name>
   <tag></tag>
   <elementGuidId>421db520-b101-4af1-9895-458ef2bcc69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq24n1duUby7_ontEGVpUmaY9wzqkD89UbOGPsZ4291jFR0294Y-vubb4MOOtn6ws2572_jFwrtgCKk5UmsYTbE4f7h0DslqRqFo2LoVbsZ9ZuhNGaKzrlDvDX1f8cWv3-k7jP61kiWJIm45l6UhwV_ykUllk2w3gb9BVNeBXvh98R-Gf8fwhbpb1kG2sjTtmqqeMAxI8&amp;k=6LdShToUAAAAAOIhE7oWA-YalXGYv3KnRnokkunq</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Formularz/Page_Aptekarska Szkoa Zarzdzania/iframe_Niepoprawny adres email_c-6mxxpk82ip3v</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq24n1duUby7_ontEGVpUmaY9wzqkD89UbOGPsZ4291jFR0294Y-vubb4MOOtn6ws2572_jFwrtgCKk5UmsYTbE4f7h0DslqRqFo2LoVbsZ9ZuhNGaKzrlDvDX1f8cWv3-k7jP61kiWJIm45l6UhwV_ykUllk2w3gb9BVNeBXvh98R-Gf8fwhbpb1kG2sjTtmqqeMAxI8&amp;k=6LdShToUAAAAAOIhE7oWA-YalXGYv3KnRnokkunq')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
