<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_czytaj wicej_ultsl-arrow-right6</name>
   <tag></tag>
   <elementGuidId>2c074c0d-efff-426b-824d-727c7ae65651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ultsl-arrow-right6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ultsl-arrow-right6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ult-carousel-165706995560115ca35ecad&quot;)/div[@class=&quot;ult-carousel-264757537060115ca35ec8d slick-initialized slick-slider&quot;]/button[@class=&quot;slick-next default slick-arrow&quot;]/i[@class=&quot;ultsl-arrow-right6&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ult-carousel-165706995560115ca35ecad']/div/button[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
