<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Kontakt_ultsl-arrow-right4</name>
   <tag></tag>
   <elementGuidId>28916470-cf25-4c40-a066-0c2b9fafc056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ultsl-arrow-right4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ult-carousel-390239645160115c3d3ec06']/div/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ultsl-arrow-right4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ult-carousel-390239645160115c3d3ec06&quot;)/div[@class=&quot;ult-carousel-330497995760115c3d3ebde slick-initialized slick-slider&quot;]/button[@class=&quot;slick-next default slick-arrow&quot;]/i[@class=&quot;ultsl-arrow-right4&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ult-carousel-390239645160115c3d3ec06']/div/button[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
