<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Wicej o nas_vc_single_image-img attachm_21fb2b</name>
   <tag></tag>
   <elementGuidId>b1225e67-b4af-46a4-b890-8d26253e0cde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.vc_single_image-img.attachment-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>800</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>533</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.aptekarska.pl/wp-content/uploads/2020/10/Depositphotos_60188291_xl-2015-1.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc_single_image-img attachment-full</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://www.aptekarska.pl/wp-content/uploads/2020/10/Depositphotos_60188291_xl-2015-1.jpg 800w, https://www.aptekarska.pl/wp-content/uploads/2020/10/Depositphotos_60188291_xl-2015-1-300x200.jpg 300w, https://www.aptekarska.pl/wp-content/uploads/2020/10/Depositphotos_60188291_xl-2015-1-768x512.jpg 768w, https://www.aptekarska.pl/wp-content/uploads/2020/10/Depositphotos_60188291_xl-2015-1-600x400.jpg 600w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 800px) 100vw, 800px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dt-location</name>
      <type>Main</type>
      <value>https://www.aptekarska.pl/home/smiling-pharmacist-promoting-a-product/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;vc_row wpb_row vc_row-fluid vc_custom_1608590937016 vc_row-o-equal-height vc_row-flex ult-vc-hide-row vc_row-has-fill&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-12&quot;]/div[@class=&quot;vc_column-inner vc_custom_1578567981045&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;vc_row wpb_row vc_inner vc_row-fluid&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-6&quot;]/div[@class=&quot;vc_column-inner&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;wpb_single_image wpb_content_element vc_align_left wpb_animate_when_almost_visible wpb_fadeIn fadeIn wpb_start_animation animated&quot;]/figure[@class=&quot;wpb_wrapper vc_figure&quot;]/div[@class=&quot;vc_single_image-wrapper vc_box_outline  vc_box_border_grey&quot;]/img[@class=&quot;vc_single_image-img attachment-full&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[4]/div[2]/div/div/div[2]/div[2]/div/div/div/figure/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.aptekarska.pl/wp-content/uploads/2020/10/Depositphotos_60188291_xl-2015-1.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/img</value>
   </webElementXpaths>
</WebElementEntity>
